add_newline = true
line_break.disabled = true

right_format = """$time"""

[time]
disabled = true
format = '[$time](#4C566A)'
time_format = "%T"

[directory]
format = "[$read_only](red)[ ](blue)[$path](italic #4C566A) "
read_only = " "
fish_style_pwd_dir_length = 1
truncation_length = 4

[character]
error_symbol = "[ ](red)"
success_symbol = "[ ](green)"
vicmd_symbol = "[ ](yellow)"

[package]
symbol = " "

[nodejs]
format = "via [ $version](bold yellow) "

[python]
symbol = " "

[lua]
format = "via [ $version](bold yellow) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold green"

[cmake]
format = "via [卑$version](bold #B48EAD) "

[golang]
symbol = "ﳑ "

[custom.docker]
command = "docker version -f '{{.Server.Version}}' 2>/dev/null"
files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
style = "blue bold"
symbol = " v"
format = "via [$symbol$output]($style) "

[git_status]
style = "bold red"
ahead = '[  $count](bold green)'
behind = '[  $count](bold green)'
untracked = '[  $count](bold yellow)'
modified = '[  $count](bold #D08770)'
staged = '[  $count](bold green)'
renamed = '[  $count](bold yellow)'
deleted = '[ $count](bold red)'
conflicted = '[ﮗ $count](bold cyan)'
diverged = '[↕ ${ahead_count}⇣${behind_count}](bold cyan)'
stashed = '[ﰩ $count](bold yellow)'
