add_newline = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = true

[character]
success_symbol = "[âžœ](bold cyan)"
error_symbol = "[âœ—](bold red)"


[package]
symbol = "ï£” "

[nodejs]
symbol = "ïŸ— "

[python]
symbol = "îœ¼ "

[lua]
symbol= "î˜  "

[git_branch]
symbol= "ïˆ îœ¥ "

[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = "â‡¡$count "
behind = "â‡£$count "
deleted = "ðŸ—‘ $count "
diverged = "ï—º$count "
stashed = "ðŸ“¦$count "
modified = "ïƒ¬ $count "
staged = '[ï§$count ](green)'
renamed = "ï‘š $count "
untracked = "ðŸ¤·â€$count "
style = "red"

[cmake]
symbol = "ï¨µ "

[golang]
symbol = "ï³‘ "

[directory]
read_only = " ï¬² "
read_only_style = "yellow"
style = "green"
truncation_length = 3 
truncation_symbol = "~~/"
home_symbol = "~"

[custom.docker]
command = "docker version -f '{{.Server.Version}}' 2>/dev/null"
files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
style = "blue bold"
symbol = "ïŒˆ v"
format = "via [$symbol$output]($style) "

